title: 小区汇 # your site title
author: liushaofeng89
email: liushaofeng89@qq.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  个人站点用途，分享日常生活
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.xqhui.cc" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: liushaofeng89 # replace with your_twitter_username or comment to remove link from footer
github_username:  liushaofeng89 # replace with your_github_username or comment to remove link from footer
instagram_username: liushaofeng89 # replace with your_instagram_username or comment to remove link from footer
social:
  name: Fengshao
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/liushaofeng89
    - https://keybase.io/benbalter

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: 
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
